/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diusmartcity;

import java.awt.Color;
import java.sql.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SRJOY
 */
public class Admission extends javax.swing.JFrame {

    /**
     * Creates new form Admission
     */
    public  Connection conn=null;
    public Admission() {
        initComponents();
        jPanel2.setBackground(new Color(0,0,0,65));
        DatabaseConnection Database = new DatabaseConnection();
        conn = Database.getcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        logoText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        gpaField = new javax.swing.JTextField();
        fatherField = new javax.swing.JTextField();
        motherField = new javax.swing.JTextField();
        nationalityField = new javax.swing.JTextField();
        admissionButton = new javax.swing.JButton();
        navBackButton = new javax.swing.JButton();
        departmentCombo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox<>();
        bloodCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        closeButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diusmartcity/admission.jpg"))); // NOI18N

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diusmartcity/admission.gif"))); // NOI18N
        getContentPane().add(logoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 29, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 96, 1250, 10));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name (Full-Name)*");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone*");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 105, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address*");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, 114, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GPA (SSC+HSC)*");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Father's Name*");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 288, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mother's Name*");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 366, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nationality*");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 447, 114, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Department*");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 19, 150, -1));

        nameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 16, 225, -1));

        phoneField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 75, 225, -1));

        addressField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 138, 225, -1));

        gpaField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(gpaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 218, 225, -1));

        fatherField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(fatherField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 285, 225, -1));

        motherField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(motherField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 366, 225, -1));

        nationalityField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(nationalityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 444, 225, -1));

        admissionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diusmartcity/submit.png"))); // NOI18N
        admissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissionButtonActionPerformed(evt);
            }
        });
        jPanel2.add(admissionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, -1, -1));

        navBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diusmartcity/back.png"))); // NOI18N
        navBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBackButtonActionPerformed(evt);
            }
        });
        jPanel2.add(navBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, -1, -1));

        departmentCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        departmentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "EEE", "Pharmacy", "BBA", "NFE" }));
        departmentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboActionPerformed(evt);
            }
        });
        jPanel2.add(departmentCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 97, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 1230, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender*");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Blood Group*");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 160, -1));

        genderCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel2.add(genderCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 100, -1));

        bloodCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bloodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+ve", "A-ve", "B+ve", "B-ve", "O+ve", "O-ve", "AB+ve", "AB-ve" }));
        jPanel2.add(bloodCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 100, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diusmartcity/admission.jpg"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 117, 1250, 590));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diusmartcity/close.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 30, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diusmartcity/admission1.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void navBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBackButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_navBackButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_closeButtonActionPerformed

    public String givenUsingJava8_whenGeneratingRandomAlphanumericString_thenCorrect() {
    int leftLimit = 48; // numeral '0'
    int rightLimit = 122; // letter 'z'
    int targetStringLength = 10;
    Random random = new Random();

    String generatedString = random.ints(leftLimit, rightLimit + 1)
      .filter(i -> (i <= 57 || i >= 65) && (i <= 90 || i >= 97))
      .limit(targetStringLength)
      .collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append)
      .toString();

    return generatedString;
}
    
    private void admissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissionButtonActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText();
        String address = addressField.getText();
        String phone = phoneField.getText();
        Double gpa = Double.parseDouble(gpaField.getText());
        String fatherName = fatherField.getText();
        String motherName = motherField.getText();
        String nationality = nationalityField.getText();
        String department = departmentCombo.getSelectedItem().toString();
        String gender = genderCombo.getSelectedItem().toString();
        String bloodGroup = bloodCombo.getSelectedItem().toString();
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());  
        String timeStamp=timestamp.toString();  
        String password = givenUsingJava8_whenGeneratingRandomAlphanumericString_thenCorrect();
        
        Student s = new Student(name,phone,address,gpa,fatherName,motherName,nationality,department,gender,bloodGroup);
        
        try {
            String QUERY = "SELECT COUNT(*) AS rowcount FROM student where phone='"+phone+"'";
            
            Statement stmt = conn.createStatement();
            
            ResultSet rs = stmt.executeQuery(QUERY);
            
            rs.next();
            int count = rs.getInt("rowcount") ;
            
            if(count>0) {
                JOptionPane.showMessageDialog(null, "Already admitted", "Warning",JOptionPane.ERROR_MESSAGE);
            }else {
                String sql = "INSERT INTO student( name, password, phone, address, gpa, father, mother, nationality, department, gender, bloodGroup, email, waiver, paid, payable, date) VALUES ('"+name+"','"+password+"','"+phone+"','"+address+"','"+gpa+"','"+fatherName+"','"+motherName+"','"+nationality+"','"+department+"','"+gender+"','"+bloodGroup+"','"+s.getEmail()+"','"+s.getWaiver()+"','"+s.getPaid()+"','"+s.getPayable()+"','"+timeStamp+"')";

                 if(name.equals("") || gpa.equals("") || department.equals("")) {
                    System.out.println("Please Fill Out the Form");
                }else {
                    try{
                            stmt.execute(sql);
                            JOptionPane.showMessageDialog(null, "Admission Successful\nEmail: '"+s.getEmail()+"'\nPassword: '"+password+"'", "Success",JOptionPane.INFORMATION_MESSAGE);
                    }catch(SQLException e) {
                        System.out.println("SQL wrong :"+e);
                    }
                }
            }
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_admissionButtonActionPerformed

    private void departmentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JButton admissionButton;
    private javax.swing.JComboBox<String> bloodCombo;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> departmentCombo;
    private javax.swing.JTextField fatherField;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JTextField gpaField;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoText;
    private javax.swing.JTextField motherField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nationalityField;
    private javax.swing.JButton navBackButton;
    private javax.swing.JTextField phoneField;
    // End of variables declaration//GEN-END:variables
}
