/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diusmartcity;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SRJOY
 */
public class Library extends javax.swing.JFrame {

    /**
     * Creates new form Library
     */
    
    private int studentId;
     public  Connection conn=null;
     DatabaseConnection Database = new DatabaseConnection();
    public Library() {
        initComponents();
    }
    public Library(int id){
        
        DatabaseConnection Database = new DatabaseConnection();
        conn = Database.getcon();
        initComponents();
        DefaultTableModel tblModel = (DefaultTableModel)bookTable.getModel();
        this.studentId = id;
        try {
                String SQLL = "SELECT * FROM studentBook where studentId='"+this.studentId+"'";
                try (Statement stmt = conn.createStatement()) {
                    ResultSet rs = stmt.executeQuery(SQLL);

                    while(rs.next()){
                        String bookNo = Integer.toString(rs.getInt("bookNo"));
                        String bookName = rs.getString("bookName");
                        String date = rs.getString("date");
                        
                        
                        String tbData[] = {bookNo,bookName,date};
                        
                        tblModel.addRow(tbData);

                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(Library.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        bookTermField = new javax.swing.JTextField();
        bookSearchButton = new javax.swing.JButton();
        bookNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bookNoField = new javax.swing.JTextField();
        bookCatField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookSelfField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        borrowButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        navBackButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diusmartcity/library.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 19, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 1260, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 50, 453));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 1260, 10));
        getContentPane().add(bookTermField, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 126, 225, -1));

        bookSearchButton.setBackground(new java.awt.Color(0, 255, 255));
        bookSearchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookSearchButton.setText("Search");
        bookSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bookSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 122, -1, -1));

        bookNameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bookNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 248, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 89, -1));

        bookNoField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bookNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 248, -1));

        bookCatField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bookCatField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 248, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 89, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 89, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Self No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        bookSelfField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bookSelfField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 248, -1));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Issue Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, 359));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Books should be Return with in 14 days");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 700, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 51));
        jLabel7.setText("Your Registered Books");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, -1, -1));

        returnButton.setBackground(new java.awt.Color(255, 153, 153));
        returnButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 617, -1, -1));

        borrowButton.setBackground(new java.awt.Color(153, 255, 0));
        borrowButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        borrowButton.setText("Borrow");
        borrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(borrowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("x");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1229, 19, -1, 34));

        navBackButton.setBackground(new java.awt.Color(255, 255, 51));
        navBackButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        navBackButton.setText("Back");
        navBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(navBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 630, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diusmartcity/library.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void navBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBackButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new StudentPortal().setVisible(true);
    }//GEN-LAST:event_navBackButtonActionPerformed

    private void bookSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSearchButtonActionPerformed
        // TODO add your handling code here:
        String term = bookTermField.getText();
        try {
            String QUERYY = "SELECT COUNT(*) AS rowcount FROM book where bookNo='"+term+"'";
            Statement stmt = conn.createStatement();
            
            ResultSet rss = stmt.executeQuery(QUERYY);
            rss.next();
            int count = rss.getInt("rowcount") ;
            if(count>0) {
                String QUERY = "SELECT * FROM book where bookNo='"+term+"'";
                try{
                    ResultSet rs = stmt.executeQuery(QUERY);
                    rs.next();
                    bookNameField.setText(rs.getString("bookName"));
                    bookNoField.setText(rs.getString("bookNo"));
                    bookCatField.setText(rs.getString("category"));
                    bookSelfField.setText(rs.getString("self"));
                }catch(SQLException ex) {
                    Logger.getLogger(Library.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else {
                JOptionPane.showMessageDialog(null, "No Book Found","Nothing Found",JOptionPane.INFORMATION_MESSAGE);
            }
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Library.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bookSearchButtonActionPerformed

    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowButtonActionPerformed
        // TODO add your handling code here:
        if(bookCatField.equals("") && bookNameField.equals("") && bookNoField.equals("") && bookSelfField.equals("")){
            JOptionPane.showMessageDialog(null, "Please Select a Book by searching with Book Number","Book Selection",JOptionPane.OK_OPTION);
        }else {
            int bookNo = Integer.parseInt(bookNoField.getText());
            int studentId = this.studentId;
            String bookName = bookNameField.getText();
            Timestamp timestamp = new Timestamp(System.currentTimeMillis());  
            String timeStamp=timestamp.toString();  
            String sql = "INSERT INTO studentBook(studentId, bookNo, bookName, date) VALUES ('"+studentId+"','"+bookNo+"','"+bookName+"','"+timeStamp+"')";
            try{
                try (Statement stmt = conn.createStatement()) {
                    stmt.execute(sql);
                    JOptionPane.showMessageDialog(null, "Your Borrowed Book No '"+bookNo+"'\nPlease Return the Book within 10 days","Book Borrow Confirmation",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    new Library(this.studentId).setVisible(true);
                }
            }catch(SQLException e) {
                System.out.println("SQL wrong :"+e);
            }
        }
    }//GEN-LAST:event_borrowButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        if(bookCatField.equals("") && bookNameField.equals("") && bookNoField.equals("") && bookSelfField.equals("")){
            JOptionPane.showMessageDialog(null, "Please Select a Book by searching with Book Number","Book Selection",JOptionPane.OK_OPTION);
        }else {
            int bookNo = Integer.parseInt(bookNoField.getText());
            String sql = "delete from studentBook where studentId='"+this.studentId+"' and bookNo='"+bookNo+"'";
            try {
                Statement st = conn.createStatement();
               st.execute(sql);
               st.close();
               JOptionPane.showMessageDialog(null, "Your Returned Book No '"+bookNo+"'\nNever Stop Learning!","Book Return Confirmation",JOptionPane.OK_OPTION);
               dispose();
                new Library(this.studentId).setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookCatField;
    private javax.swing.JTextField bookNameField;
    private javax.swing.JTextField bookNoField;
    private javax.swing.JButton bookSearchButton;
    private javax.swing.JTextField bookSelfField;
    private javax.swing.JTable bookTable;
    private javax.swing.JTextField bookTermField;
    private javax.swing.JButton borrowButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton navBackButton;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
